"""
Traffic Validator.

Analyzes the output strings generated by the TrafficGenerator to compute 
latency, packet loss, and verify payload integrity.
"""

from dataclasses import dataclass
from typing import Tuple

@dataclass
class TrafficResult:
    """Immutable record of a validated traffic transaction."""
    protocol: str
    success: bool
    latency_ms: float
    payload_match: bool
    error_msg: str = ""


class TrafficValidator:
    """Validates connectivity and extracts RTT metrics."""

    @staticmethod
    def validate_icmp(success: bool, output: str) -> TrafficResult:
        """Parses ping output."""
        latency = 0.0
        if success and "1 received" in output:
            try:
                # Extract time=X.XXX ms
                time_str = output.split("time=")[1].split(" ")[0]
                latency = float(time_str)
            except IndexError:
                pass
            return TrafficResult("ICMP", True, latency, True)
        return TrafficResult("ICMP", False, 0.0, False, output)

    @staticmethod
    def _parse_python_output(success: bool, output: str, expected_payload: str, proto: str) -> TrafficResult:
        """Parses the 'latency|payload' format from inline python scripts."""
        if not success:
            return TrafficResult(proto, False, 0.0, False, output)
            
        try:
            parts = output.split("|", 1)
            latency = float(parts[0]) * 1000  # convert to ms
            payload = parts[1].strip()
            
            payload_match = payload == expected_payload
            return TrafficResult(proto, True, latency, payload_match, "" if payload_match else f"Got '{payload}'")
        except Exception as e:
            return TrafficResult(proto, False, 0.0, False, f"Parsing error: {e}")

    @classmethod
    def validate_tcp(cls, success: bool, output: str, expected: str = "TCP_TEST") -> TrafficResult:
        return cls._parse_python_output(success, output, expected, "TCP")

    @classmethod
    def validate_udp(cls, success: bool, output: str, expected: str = "UDP_TEST") -> TrafficResult:
        return cls._parse_python_output(success, output, expected, "UDP")

    @classmethod
    def validate_http(cls, success: bool, output: str) -> TrafficResult:
        return cls._parse_python_output(success, output, "HTTP_PAYLOAD_OK", "HTTP")

    @classmethod
    def validate_dns(cls, success: bool, output: str) -> TrafficResult:
        return cls._parse_python_output(success, output, "OK", "DNS")